/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ChaiBhe.newpackage;


import java.text.DecimalFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thana
 */
public class window extends javax.swing.JFrame {
    //ราคารายการอาหาร
    String price[]={"30","35","40","35","30","35","35","30","30"};
    //สร้างโมเดลตาราง
    DefaultTableModel model;
    //สร้าง comma
    DecimalFormat df=new DecimalFormat("#,###.00");
    //หาราคารวม
    double total=0.0;
    //เก็บแถวที่ผู้ใช้เลือก
    int selected;
    //เก็บตำแหน่งที่ซ้ำ
    int n;
    //เก็บราคารวม
    double money;
    public window() {
        initComponents();
        t1.setText(price[0]);
        model=(DefaultTableModel)tb.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbMenu = new javax.swing.JComboBox<>();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        bm1 = new javax.swing.JButton();
        bm2 = new javax.swing.JButton();
        bm3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        lbtotal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("รายการอาหาร");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 152, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("ราคา/ชุด");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 214, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("จำนวน");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        cbMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "บะหมี่เกี๊ยวหมูแดง", "บะหมี่เกี๊ยวหมูกรอบ", "บะหมี่เกี๊ยวปู", "บะหมี่เกี๊ยวขาหมู", "เส้นเล็กหมูแดง", "เส้นเล็กหมูกรอบ", "เส้นเล็กขาหมู", "เย็นตาโฟเส้นเล็ก", "เย็นตาโฟเส้นใหญ่" }));
        cbMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMenuActionPerformed(evt);
            }
        });
        getContentPane().add(cbMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 152, 254, 29));

        t1.setEnabled(false);
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 90, 29));

        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 80, 29));

        bm1.setText("เพิ่ม");
        bm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bm1ActionPerformed(evt);
            }
        });
        getContentPane().add(bm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 257, 70, 42));

        bm2.setText("ลบ");
        bm2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bm2MouseClicked(evt);
            }
        });
        bm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bm2ActionPerformed(evt);
            }
        });
        getContentPane().add(bm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 257, 70, 42));

        bm3.setText("แก้ไข");
        bm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bm3ActionPerformed(evt);
            }
        });
        getContentPane().add(bm3, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 257, 70, 42));

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "รายการอาหาร", "ราคา/ชุด", "จำนวน", "จำนวนเงิน"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb);
        if (tb.getColumnModel().getColumnCount() > 0) {
            tb.getColumnModel().getColumn(0).setResizable(false);
            tb.getColumnModel().getColumn(1).setResizable(false);
            tb.getColumnModel().getColumn(2).setResizable(false);
            tb.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 317, 581, 194));

        lbtotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbtotal.setText("ราคารวม");
        getContentPane().add(lbtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 517, 335, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("ร้านบะหมี่ ChaiBhe");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 39, 300, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ChaiBhe/newpackage/4564564.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        
    }//GEN-LAST:event_t2ActionPerformed

    private void cbMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMenuActionPerformed
        t1.setText(price[cbMenu.getSelectedIndex()]);
    }//GEN-LAST:event_cbMenuActionPerformed

    private void bm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bm1ActionPerformed
        Vector v=new Vector();
        if(t2.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"กรุณาป้อนจำนวนอาหาร","คำเตือน",JOptionPane.ERROR_MESSAGE);
        }if(checkMenu()){
            int a=Integer.parseInt(model.getValueAt(n,2).toString())+Integer.parseInt(t2.getText());
            System.out.println("a="+a);
            model.setValueAt(a,n,2);
            double price=a*Double.valueOf(tb.getValueAt(n,1).toString());
            System.out.print("ราคาใหม่="+price);
            model.setValueAt(df.format(price),n,3);
            money=Double.valueOf(t1.getText())*Double.valueOf(t2.getText());
            total+=money;
            lbtotal.setText("ราคารวม : "+df.format(total)+"บาท");
        }else{
            v.add(cbMenu.getSelectedItem().toString());
            v.add(t1.getText());
            v.add(t2.getText());
            money=Double.valueOf(t1.getText())*Double.valueOf(t2.getText());
            v.add(df.format(money));
            total+=money;
            model.addRow(v);
            lbtotal.setText("ราคารวม : "+df.format(total)+"  บาท  ");
        }     
    }//GEN-LAST:event_bm1ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void bm2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bm2MouseClicked

    }//GEN-LAST:event_bm2MouseClicked

    private void bm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bm2ActionPerformed
        if(tb.isRowSelected(selected)){
            double moneySelected=Double.valueOf(tb.getValueAt(selected,3).toString().replace(",",""));
            System.out.println("แสดงจำนวนเงิน"+moneySelected);
            total-=moneySelected;
            lbtotal.setText("ราคารวม : "+df.format(total)+"  บาท  ");
            if(total==0){
                lbtotal.setText("ราคารวม : 0.00 บาท  ");
            }
            model.removeRow(selected);
        }else{
            JOptionPane.showMessageDialog(this,"กรุณาเลือกแถวในตาราง","คำเตือน",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bm2ActionPerformed

    private void tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMouseClicked
        selected=tb.getSelectedRow();
        String name =tb.getValueAt(selected,0).toString();
        System.out.println("Name = "+name);
        System.out.println("แถวที่เลือก="+selected);
        t2.setText(tb.getValueAt(selected,2).toString());
        for(int i = 0; i < cbMenu.getItemCount(); i++){
            if(name.equals(cbMenu.getItemAt(i))){
                cbMenu.setSelectedIndex(i);
            }
        }
    }//GEN-LAST:event_tbMouseClicked

    private void bm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bm3ActionPerformed
        double before=Double.valueOf(tb.getValueAt(selected,1).toString())*Double.valueOf(tb.getValueAt(selected,2).toString());
        System.out.println("before = "+before);
        tb.setValueAt(t2.getText(),selected,2);
        int amount=Integer.valueOf(t2.getText());
        double bnew=amount*Double.valueOf(tb.getValueAt(selected,1).toString());
        tb.setValueAt(df.format(bnew),selected,3);
        total = total-before+bnew;
        lbtotal.setText("ราคารวม : "+df.format(total)+"  บาท  ");
    }//GEN-LAST:event_bm3ActionPerformed
    public boolean checkMenu(){
        for (int i = 0; i < tb.getRowCount(); i++){
            if(cbMenu.getSelectedItem().toString().equals(tb.getValueAt(i,0))){
                n=i;
                System.out.println("รายการอาหารซ้ำกัน"+"ที่แถว = "+n);
                return true;  
            }  
        }
        return false;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bm1;
    private javax.swing.JButton bm2;
    private javax.swing.JButton bm3;
    private javax.swing.JComboBox<String> cbMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbtotal;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTable tb;
    // End of variables declaration//GEN-END:variables
}
